site_name: React in Meteor Preview (Unreleased)
theme: readthedocs
pages:
- Getting started: index.md
- Tutorial: tutorial.md
- Reactive Meteor data in React: meteor-data.md
- JSX transpilation and ES6 features: jsx.md
- React components inside Meteor templates: react-template-helper.md