site_name: React in Meteor
theme: readthedocs
pages:
- Getting started: index.md
- Tutorials: tutorial.md
- Reactive Meteor data in React: meteor-data.md
- JSX transpilation and ES6 features: jsx.md
- Client NPM packages with Browserify: client-npm.md
- React components in Meteor templates: react-template-helper.md
- Setting up routing with React: routing.md
- Community Meteor + React tools: community.md
extra_javascript:
- analytics.js
